# Generated by Django 3.2 on 2021-04-21 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submission.misc_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RJ', 'Rejected'), ('AC', 'Accepted'), ('UR', 'Under Review')], default='UR', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('approx_bats', models.PositiveIntegerField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('rejected_time', models.DateTimeField(blank=True, null=True)),
                ('photo_taken_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=submission.misc_functions.image_name)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='submission.submission')),
            ],
        ),
    ]
