# Generated by Django 3.2 on 2021-06-26 06:05

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
