# Generated by Django 3.2 on 2021-06-26 12:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
