# Generated by Django 3.2 on 2021-06-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_rename_geom_submission_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='location',
            new_name='geom',
        ),
    ]
